id: 3c2a4bff3ddb4fc3a05da91b398cdbf9
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_113-The_White_Lotus_of_the_Good_Dharma-v1
  language: en
  author: ''
  volume: {}
